### ISSUE TITLE
Loading Vault secrets into non-top-level Pillar keys

### ISSUE THREAD

**Issue by xenophonf** [ripple/salt-pillar-vault#2]
Elsewhere, I might have a Salt formula that expects an X.509 key pair stored in Pillar keys that aren't at the top level:

```yaml
foobar-app:
  pubkey: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  privkey: |
    -----BEGIN PRIVATE KEY-----
    ...
    -----END PRIVATE KEY-----
```

Is it possible to tell salt-pillar-vault to load the above key-pair from Vault and put it into `foobar-app:pubkey` and `foobar-app:privkey` (which I would assume gets merged with other Pillar data sources in the usual way)?  If not, is that what #1 will add?

**Comment by cinterloper** [comment]
There is an open PR for this feature 
https://github.com/ripple/salt-pillar-vault/issues/2
so soon, this should be available.
