### ISSUE TITLE
NoneType error

### ISSUE THREAD

**Issue by mvam75** [ripple/salt-pillar-vault#3]
hi there - 

wondering if you could help out really quick?

when i refresh my pillar data, the salt master log prints out:

`[salt.pillar      ][CRITICAL][13818] Pillar render error: Failed to load ext_pillar vault_store: 'NoneType' object has no attribute '__getitem__'`

I'm pretty sure i've got the configuration right, here it is:

`ext_pillar:
  - vault_store:
      url: https://vault.url:8200
      config: /etc/salt/config.yml
      token: redacted
      unset_if_missing: True`

here is my config yaml

`'*':
  'aws_key_id': 'secret/service/salt/dev/aws-access-key?id'
  'aws_secret_key': 'secret/service/salt/dev/aws-secret-access-key?secret'`

i've made sure that the token can read and write to that path in Vault and that the salt master can reach the vault server.

Not too sure what to do at this point.

**Comment by mvam75** [comment]
nevermind - i'm an idiot. got it worked out.

**Comment by cinterloper** [comment]
There are no dumb questions!
would you mind sharing the issue/solution so that others in the future that may find this thread can know what the answer is?

**Comment by mvam75** [comment]
It turned out i had my config wrong

`'aws_secret_key': 'secret/service/salt/dev/aws-secret-access-key?secret'`

needed to be

`'aws_secret_key': 'secret/service/salt/dev/aws-access-key?secret'`
