### ISSUE TITLE
running with a masterless minion?

### ISSUE THREAD

**Issue by mvam75** [ripple/salt-pillar-vault#4]
Another issue :-)

Trying to run the plugin in vagrant with a masterless minion, but there seems to be a problem with the minion matching

```
2016-11-17 21:23:04,842 [salt.template    ][DEBUG   ][31381] Rendered data from file: /vagrant/salt/srv/salt/common/vault-config.yml:
'amperity-vbox':
  'vault':
    'aws_key_id': 'secret/service/salt/vagrant/aws-access-key?id'
    'aws_secret_key': 'secret/service/salt/vagrant/aws-access-key?secret'

2016-11-17 21:23:04,843 [salt.utils.minions][DEBUG   ][31381] _check_compound_minions(amperity-vbox, :, True, False)
2016-11-17 21:23:04,843 [salt.utils.minions][ERROR   ][31381] Failed matching available minions with compound pattern: amperity-vbox
```

I've tried other standard patterns for compound matching even '*', but nothing seems to work.

**Comment by mvam75** [comment]
something interesting

`2016-11-17 21:23:04,847 [salt.minion      ][DEBUG   ][31381] compound_match amperity-vbox ? "*" => "True"`

which happens *after* the external pillar is loaded

**Comment by cinterloper** [comment]
We have not tested in masterless mode during development.

your issue may, or may not, be related to
https://github.com/saltstack/salt/issues/26035

If you would like to submit a patch to support masterless mode, id be happy to take a look at it

**Comment by mvam75** [comment]
I did see that, and thats most likely the issue. For now I've gone with running a salt-master in the vbox instance.

**Comment by mvam75** [comment]
closing this since running with a salt master fixes things
